config/routes.rb
Rails.application.routes.draw do

  resources :flyers do
    member do
      get :personalize
      get :send_email
    end
  end
  resources :plans
  resources :subscriptions

  get 'admin', to: 'admin/dashboards#index'
  get 'generate/subscription'
  get 'dispatcher/start'
  get 'dispatcher/pages_user_profile'
  get 'dispatcher/send'

  devise_for :users

  namespace :admin do
    resources :static_pages
    resources :templates
    resources :plans
    resources :users
    resources :realtors
  end

  ['welcome', 'coverage_and_pricing', 'create_a_flyer',
   'how_it_works', 'about_us', 'faq', 'contact_us'].each do
    |method|
    if method == 'welcome'
      root "static_pages##{method}"  
    else
      get "/#{method}", to: "static_pages##{method}"        
    end
  end

end

app/models/flyer.rb
class Flyer < ActiveRecord::Base
  extend Displayable

  belongs_to :user
  validates_presence_of :user_id

  has_many :photos, as: :assetable, dependent: :destroy
  accepts_nested_attributes_for :photos, :reject_if => :all_blank, :allow_destroy => true

end

app/controllers/flyers_controller.rb
require 'mailgun'

class FlyersController < ApplicationController
  before_filter :authenticate_user!

  # GET /flyers
  # GET /flyers.json
  def index
    
  end

  def personalize
    @template = Template.find(params[:id])
    @flyer = current_user.flyers.create(flyer_params(make_params ( @template.template_properties )))
    @flyer.save
    render 'edit'
  end

  def edit

  end

  def show
  end

  def update
    respond_to do |format|
      if flyer.update(flyer_params)
        format.html { redirect_to @flyer, notice: 'Flyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @flyer }
      else
        format.html { render :edit }
        format.json { render json: @flyer.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_email
    mg_client = Mailgun::Client.new Rails.application.secrets.bareed_key
    @response = mg_client.send_message 'sandbox5174d49fc72642e7831b266b19a0cbd4.mailgun.org', flyer.email_message
    @response = ActiveSupport::JSON.decode(@response.body)["message"]
    respond_to do |format|
      format.js 
      format.html { render nothing: true }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def flyer_params(args = nil)
    if [:create, :update].include? action_name
      (args || params).require(:flyer).permit(:name, :description, :content)
    end
  end

  def template_params(args = nil)
    if [:create, :update].include? action_name
      (args || params).require(:template).permit(:name, :description, :content)
    end
  end

  def template
    @template ||= TemplateDecorator.new(params[:id].present? ? Template.find(params[:id]) : Template.new(template_params) )
  end
  helper_method :template

  def templates
    @templates ||= TemplatesDecorator.new(Template.order(:updated_at).page(params[:template]), TemplateDecorator)
  end
  helper_method :templates

  def flyer
    @flyer ||= FlyerDecorator.new(params[:id].present? ? Flyer.find(params[:id]) : Flyer.new(flyer_params) )
  end
  helper_method :flyer

  def flyers
    @flyers ||= FlyersDecorator.new(Flyer.order(:updated_at).page(params[:flyer]), FlyerDecorator)
  end
  helper_method :flyers

  def make_params(template_hash)
    h = ActiveSupport::HashWithIndifferentAccess[flyer: template_hash]
    ActionController::Parameters.new(h)
  end

end

app/helpers/flyers_helper.rb
module FlyersHelper
end

app/views/flyers/_editable.html.erb
<div class="main-container ">
  <section class="page-top">
    <div class="container">
      <div class="row">
	<p id="notice"><%#= notice %></p>
	<div class="col-md-6">
	  <p><strong>Name:</strong> <%= flyer.name %></p>
	  <%= link_to 'Back', flyers_path, class: 'btn btn-tiny btn-primary' %>
	</div>
	<div class="col-md-6">
	  <p><strong>Description:</strong>  <%= flyer.description %></p>
	</div>
      </div>
    </div>
  </section>
  <section class="wrapper">
    <div class="container">
      <div>
	<%== flyer.content_body %>
      </div>

    </section>
  </div>
</div>

app/views/flyers/edit.html.erb
<%= render 'editable' %>

<%= link_to 'Back', flyers_path %>

app/views/flyers/index.html.erb
<h1>Starter Templates</h1>

<div class='table-responsive'>
  <table class='table table-striped table-bordered'>
    <thead>
      <tr>
	<th>Name</th>
	<th>Description</th>
	<th colspan="3" class="text-center"></th>
      </tr>
    </thead>

    <tbody>
      <% templates.each do |tmpl| %>
        <tr>
          <td><%= tmpl.name %></td>
          <td><%= tmpl.description %></td>
          <td class="text-center"><%= link_to 'Make a Flyer', personalize_flyer_path(tmpl), class: 'btn btn-tiny btn-primary' %></td>
	</tr>
	<% end %>
    </tbody>
  </table>
</div>

<br>

<h1>Flyers</h1>

<div class='table-responsive'>
  <table class='table table-striped table-bordered'>
    <thead>
      <tr>
	<th>Name</th>
	<th>Description</th>
	<th colspan="3" class="text-center"></th>
      </tr>
    </thead>

    <tbody>
      <% flyers.each do |flyer| %>
        <tr>
          <td><%= flyer.name %></td>
          <td><%= flyer.description %></td>
          <td class="text-center"><%= link_to 'Edit', edit_flyer_path(flyer), class: 'btn btn-tiny btn-primary' %> <%= link_to 'Send Email', send_email_flyer_path(flyer), remote: true, class: 'btn btn-tiny btn-primary' %></td>
	</tr>
	<% end %>
    </tbody>
  </table>
</div>

<br>

app/views/flyers/new.html.erb
<h1>New flyer</h1>

<%= render 'form' %>

<%= link_to 'Back', flyers_path %>

app/views/flyers/show.html.erb
<%= render partial: 'form' %>

<%= link_to 'Back', flyers_path %>