config/routes.rb
Rails.application.routes.draw do

  resources :flyers do
    member do
      get :personalize
      get :send_email
    end
  end
  resources :plans
  resources :subscriptions

  get 'admin', to: 'admin/dashboards#index'
  get 'generate/subscription'
  get 'dispatcher/start'
  get 'dispatcher/pages_user_profile'
  get 'dispatcher/send'

  devise_for :users

  namespace :admin do
    resources :static_pages
    resources :templates
    resources :plans
    resources :users
    resources :realtors
  end

  ['welcome', 'coverage_and_pricing', 'create_a_flyer',
   'how_it_works', 'about_us', 'faq', 'contact_us'].each do
    |method|
    if method == 'welcome'
      root "static_pages##{method}"  
    else
      get "/#{method}", to: "static_pages##{method}"        
    end
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  extend Displayable
  belongs_to :plan
  attr_accessor :stripe_card_token
  
  def save_with_payment(user)
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_customer_token)
      self.stripe_customer_token = customer.id
      save!
    end
  rescue Stripe::APIError => e
    logger.error "Stripe Authentication error while creating user: #{e.message}"
    errors.add :base, "Our system is temporarily unable to process credit cards."
    false
  end

  def cancel_subscription_plan
    customer = Stripe::Customer.retrieve(stripe_customer_token)
    customer.cancel_subscription()
    user.update_attributes(:payment_status => false)
    true
  rescue Stripe::APIError => e
    logger.error "Stripe access error while cancelling subscription plan: #{e.message}"
    errors.add :base, "Our system is temporarily unable to cancel the plan, please try again after a little while."
    false
  end

  def save_plan_user(user)
    if plan.users.first.present != user
      plan.users << user
      plan.save!
    end
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
    @subscription.plan = Plan.find(params[:plan_id])
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save_with_payment(current_user)
      redirect_to @subscription, :notice => "Thank you for subscribing!"
    else
      render :new
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      if [:create, :update].include? action_name.to_sym
        params.require(:subscription).permit(:plan_id, :email, :stripe_customer_token)
      end
    end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription, html: {role: :role}) do |f| %>
  <%= form_errors(@subscription) %>

  <%= f.hidden_field :plan_id %>  
  <%= f.hidden_field :stripe_customer_token %>

  <div class="form-group">  
    <%= f.label :email %>  
    <%= f.text_field :email, class: 'form-control' %>  
  </div>    
  <% if @subscription.stripe_card_token %>  
    Credit card has been provided  
  <% else %>  
    <div class="form-group">  
       <%= label_tag :card_number, "Credit Card Number " %>  
       <%= text_field_tag :card_number, nil, name: nil, class: 'form-control' %>  
    </div>  
    <div class="form-group">  
      <%= label_tag :card_code, "Security Code on Card (CVV)" %>  
      <%= text_field_tag :card_code, nil, name: nil, class: 'form-control' %>  
    </div>  
    <div class="form-group">  
      <%= label_tag :card_month, "Card Expiration" %>  
      <%= select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month"} %>  
      <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>  
    </div>
  <% end %>  
  <%= f.submit %>
 
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<div class="container">
  <div class="row">
    <h1>Listing subscriptions</h1>

    <div class="col-md-3">
      <h3> Silver</h3>
      <p> Effective </p>
      <p><span>$9.99</span><span>/Month</span></p>
      <%= link_to 'Choose this plan', "#{new_subscription_path}/?plan_id=1", class: 'btn btn-medium btn-info' %>
      <p>
	<ul>
	  <li>5,000 emails per month</li>
	  <li>5 Flyers</li>
	</ul>
      </p>
    </div>
    <div class="col-md-3">
      <h3>Gold</h3>
      <p> Effective </p>
      <p><span>$29.99</span><span>/Month</span></p>
      <%= link_to 'Choose this plan', "#{new_subscription_path}/?plan_id=2", class: 'btn btn-medium btn-info' %>
      <p>
	<ul>
	  <li>16,000 emails per month</li>
	  <li>10 Flyers</li>
	  <li>3 Custom mailing lists</li>
	</ul>
      </p>
    </div>
    <div class="col-md-3">
      <h3>Platinum</h3>
      <p> Effective </p>
      <p><span>$49.99</span><span>/Month</span></p>
      <%= link_to 'Choose this plan', "#{new_subscription_path}/?plan_id=3", class: 'btn btn-medium btn-info' %>
      <ul>
	<li>22,000 emails per month</li>
	<li>100 Flyers</li>
	<li>10 Custom mailing lists</li>
      </ul>
    </div>
    <div class="col-md-3">
      <h3>Corporate</h3>
      <p>When you want the best</p>
      <p>Custom, contact us</p>
      <%= link_to 'Choose this plan', "#{contact_us_path}/?plan_id=4", class: 'btn btn-medium btn-info' %>
      <ul>
	<li>Tier system</li>
	<li>Unlimited Flyers</li>
	<li>Large pool of mailing lists</li>
      </ul>
    </div>
  </div>
</div>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>
<div style="margin-left: 40px;">
  <%= render 'form' %>

  <%= link_to 'Back', subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<h1>Subscription Complete</h1>

<p> Start selling your properties </p>
<p style="margin-left: 50px">
  <%= link_to 'Flyers', flyers_path, class: 'btn btn-large btn-info' %>
</p>