config/routes.rb
Rails.application.routes.draw do

  resources :flyers do
    member do
      get :personalize
      get :send_email
    end
  end
  resources :plans
  resources :subscriptions

  get 'admin', to: 'admin/dashboards#index'
  get 'generate/subscription'
  get 'dispatcher/start'
  get 'dispatcher/pages_user_profile'
  get 'dispatcher/send'

  devise_for :users

  namespace :admin do
    resources :static_pages
    resources :templates
    resources :plans
    resources :users
    resources :realtors
  end

  ['welcome', 'coverage_and_pricing', 'create_a_flyer',
   'how_it_works', 'about_us', 'faq', 'contact_us'].each do
    |method|
    if method == 'welcome'
      root "static_pages##{method}"  
    else
      get "/#{method}", to: "static_pages##{method}"        
    end
  end

end

app/models/dashboard.rb
class Dashboard
  include ActiveModel::Model
  
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @plans = Plan.order(:updated_at).page(params[:page])
    @static_pages = StaticPage.order(:updated_at).page(params[:page])
    @templates = Template.order(:updated_at).page(params[:page])
  end

end

app/views/admin/dashboards/index.html.erb
<h1>Administration Dashboard </h2>

<div>
  <h2>Registered User</h2>
  <p style='margin-left: 20px;'>
    <%= link_to 'Users', admin_users_path, class: 'btn btn-tiny btn-info' %>
  </p>
</div>

<div>
  <h2>Templates </h2>
  <%= model_tabular_content( @templates || [], {name: "Show", path: "admin_template_path"} ) %>
  <%= paginate @templates %>
  <%= link_to 'New Template', new_admin_template_path, class: 'btn btn-tiny bt-info' %>
</div>

<div>
  <h2>Credit Card Subscription Plans </h2>
  <%= model_tabular_content(@plans) %>
</div>

<div>
  <h2>HTML Static Pages</h2>
  <%= model_tabular_content( @static_pages || []) %>
  <%= paginate @static_pages %>
  <%= link_to 'New Static Page', new_admin_static_page_path, class: 'btn btn-tiny bt-info' %>
</div>

<div>
  <h2>Realtor Emails</h2>
  <p style='margin-left: 20px;'>
    <%= link_to 'Realtors', admin_realtors_path, class: 'btn btn-tiny btn-info' %>
  </p>
</div>