config/routes.rb
Rails.application.routes.draw do

  resources :flyers do
    member do
      get :personalize
      get :send_email
    end
  end
  resources :plans
  resources :subscriptions

  get 'admin', to: 'admin/dashboards#index'
  get 'generate/subscription'
  get 'dispatcher/start'
  get 'dispatcher/pages_user_profile'
  get 'dispatcher/send'

  devise_for :users

  namespace :admin do
    resources :static_pages
    resources :templates
    resources :plans
    resources :users
    resources :realtors
  end

  ['welcome', 'coverage_and_pricing', 'create_a_flyer',
   'how_it_works', 'about_us', 'faq', 'contact_us'].each do
    |method|
    if method == 'welcome'
      root "static_pages##{method}"  
    else
      get "/#{method}", to: "static_pages##{method}"        
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  extend Displayable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, 
  :validatable, :authentication_keys => [:login]

  has_many :flyers
  has_and_belongs_to_many :plans, join_table: :plans_users

  attr_accessor :login

  def login
    @login || self.username || self.email
  end

  def login=(login)
    @login = login
  end

  def email=(email)
    self[:email] = email.downcase
  end

  def username=(username)
    username.downcase
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR email = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.display_columns
    temp_display_columns.delete_if do
      |v| 
      ['id', 'created_at', 'updated_at', 'encrypted_password', 
      'reset_password_token', 'reset_password_sent_at', 'remember_created_at',
      'sign_in_count', 'current_sign_in_at', 'last_sign_in_at', 'current_sign_in_ip',
      'last_sign_in_ip'
      ].include?(v.to_s) 
    end     
  end

  def self.display_column_index
    h = Hash[column_names.map.with_index.to_a]
    h.except! display_columns
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    #authorize! :index, @user, :message => 'Not authorized as an administrator.'
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    #authorize! :create, @user, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if user.save
        format.html { redirect_to [:admin, user], notice: 'User was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    #authorize! :update, @user, :message => 'Not authorized as an administrator.'
    respond_to do |format|

      if user.update_attributes(user_params)
        format.html { redirect_to [:admin, user], notice: 'User was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    #authorize! :destroy, @user, :message => 'Not authorized as an administrator.'

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  private

  def user
    @user ||= UserDecorator.new(params[:id].present? ? User.find(params[:id]) : User.new(user_params) )
  end
  helper_method :user

  def users
    @users ||= UsersDecorator.new(User.order(:updated_at).page(params[:user]), UserDecorator)
  end
  helper_method :users

  def user_params
    if [:create, :update].include? action_name
      params.require(:user).permit(:email, :first_name, :last_name)
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @plan]) do |f| %>
  <%= form_errors(@plan) %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.number_field :frequency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @plan] %> |
<%= link_to 'Back', admin_plans_path %>

app/views/admin/users/index.html.erb
<h1>Users</h1>
  <%= model_tabular_content( users || [], {name: "Show", path: "admin_user_path"} ) %>
<br>
<%= paginate users %>

app/views/admin/users/show.html.erb
<p id="notice" style="margin-top: 30px;"><%= notice %></p>
<div class="col-sm-4">

  <h2> Profile </h2>
  <p style="margin-left: 20px;">
    <%= image_tag 'http://placehold.it/100x100' %>
  </p>

  <p style="margin-left: 10px;">
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p style="margin-left: 10px;">
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p style="margin-left: 10px;">
    <strong>Email:</strong>
    <%= user.email %>
  </p>
</div>

<div class="col-sm-8">
  <h2> Subscription Plans </h2>
     <%= link_to 'Select a Plan', subscriptions_path %>

  <p style="margin-left: 10px;">
    <%= link_to 'Edit', edit_admin_user_path([:admin, user]) %> |
    <%= link_to 'Back', admin_users_path %>
  </p>
</div>